Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.network "private_network", ip: "192.168.33.10"
    vm1.vm.network "forwarded_port", guest: 80, host: 8888


    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1"
      vb.gui = false
      vb.memory = "1024"
    end

    vm1.vm.provision "shell", inline: <<-SHELL
        useradd -m  -p '$6$enterpass$gTD3wtXzGlBI4eVdTShOaAmsL4o0K792Q/NenXmcjA1QVojSAxSNRt9a2SY/IFinTcJ2So3bhBfoFAEX2ozXY1' adminuser
        usermod -a -G admin adminuser
        useradd -m poweruser
        passwd -d poweruser
        echo 'poweruser ALL=(ALL) NOPASSWD: /usr/sbin/iptables' | sudo EDITOR='tee -a' visudo
        usermod -a -G adminuser poweruser
        ln -s /etc/mtab /home/poweruser/mylink
    SHELL
  end
  
end
